// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlftwfqnaivlxtczxtul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZnR3ZnFuYWl2bHh0Y3p4dHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODg1MzAsImV4cCI6MjA3MzM2NDUzMH0.7bUVHKViRwem_fmTps9tVhjERV6OFASb8LAXwAodNKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});